export enum PcTypesEnum {
  PERSONAL = 'PERSONAL',
  INTELLECTUAL = 'INTELLECTUAL',
  PHYSICAL = 'PHYSICAL',
  PHYSIOLOGICAL = 'PHYSIOLOGICAL',
  PSYCHO_PHYSIOLOGICAL = 'PSYCHO_PHYSIOLOGICAL',
  OPERATIONAL = 'OPERATIONAL',
}
