<?php

use models\Database;

include 'models/Database.php';
include 'models/Pvk.php';
include 'models/Profession.php';


$database = new Database();

$create_tables = [
    'CREATE TABLE IF NOT EXISTS users 
        (
            id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
            username VARCHAR(255) NOT NULL,
            email VARCHAR(255) NOT NULL UNIQUE,
            role VARCHAR(30) NOT NULL,
            password VARCHAR(255) NOT NULL,
            is_verified BOOLEAN NOT NULL
        )',
    'CREATE TABLE IF NOT EXISTS professions
        (
            id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            name VARCHAR(255) UNIQUE NOT NULL,
            description VARCHAR(255) NOT NULL,
            requirements VARCHAR(255) NOT NULL,
            sphere VARCHAR(255) NOT NULL
        )',
    'CREATE TABLE IF NOT EXISTS refresh_tokens
        (
            id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
            token VARCHAR(255) NOT NULL,
            user_id INTEGER REFERENCES users(id),
            created_at TIMESTAMP NOT NULL,
            expired_at TIMESTAMP NOT NULL
        )',
    'CREATE TABLE IF NOT EXISTS types 
        (
            id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
            name VARCHAR(255) UNIQUE NOT NULL,
            description VARCHAR(255) NOT NULL
        )',
    'CREATE TABLE IF NOT EXISTS tests 
        (
            id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
            name VARCHAR(255) UNIQUE NOT NULL,
            header VARCHAR(255) NOT NULL,
            description VARCHAR(255) NOT NULL,
            min_points INTEGER NOT NULL,
            max_points INTEGER NOT NULL,
            min_time INTEGER NOT NULL,
            max_time INTEGER NOT NULL,
            type_id INTEGER REFERENCES types(id), 
            author_id INTEGER REFERENCES users(id)
        )',
    'CREATE TABLE IF NOT EXISTS sections 
        (
            id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
            test_id INTEGER REFERENCES tests(id),
            section_type VARCHAR(255) NOT NULL,
            question VARCHAR(255) NOT NULL,
            options VARCHAR(255),
            answer VARCHAR(255)
        )',
    'CREATE TABLE IF NOT EXISTS professional_characteristics
        (
            id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
            name VARCHAR(255) UNIQUE NOT NULL,
            description VARCHAR(255) NOT NULL,
            category VARCHAR(255) NOT NULL
        )',
    'CREATE TABLE  IF NOT EXISTS verification_codes
        (
            id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
            code INTEGER NOT NULL,
            user_email VARCHAR(255) REFERENCES users(email)
        )',
    'CREATE TABLE IF NOT EXISTS professions_ratings
        (
            id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            profession_id INTEGER REFERENCES professions(id),
            pc_id INTEGER REFERENCES professional_characteristics(id),
            user_id INTEGER REFERENCES users(id),
            rating INTEGER NOT NULL
        )',
    'CREATE TABLE IF NOT EXISTS TestBlocks
        (
            id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
            name VARCHAR(255) NOT NULL,
            description VARCHAR(255) NOT NULL,
            author_id INTEGER REFERENCES users(id)
        )',
    'CREATE UNIQUE INDEX IF NOT EXISTS codes_user_email_unique ON verification_codes (user_email);',
    'ALTER TABLE professions_ratings ADD CONSTRAINT unique_professions_ratings UNIQUE (profession_id, pc_id, user_id);'
];

foreach ($create_tables as $table_query) {
    try {
        $database->createTable($table_query);
        echo "Database created!<br>";
    } catch (PDOException $e) {
        echo $e->getMessage() . "<br>";
    }
}

$professions_array =[
  [
      "Backend-Разработчик",
      "Разработчик создает серверные приложения для взаимодействия веб-сайта и базы данных. Владение языками программирования, такими как PHP, JavaScript, Java, SQL, Git, и понимание принципов работы баз данных — ключевые навыки.",
      "Навыки: PHP, JavaScript, Java, SQL, Git. Средняя зарплата: от 180 000 руб.",
      "IT"
  ],
  [
      "Frontend Разработчик",
      "Разработчик создает клиентское приложение, внешний вид веб-сайтов. Владение технологиями, такими как HTML, CSS, JavaScript, Git, и понимание принципов работы взаимодействия пользователя и браузера с содержимым веб-страниц.",
      "Навыки: HTML, CSS, JavaScript, Git. Средняя зарплата: от 170 000 руб.",
      "IT"
  ],
  [
      "Дизайнер",
      "Дизайнер создает визуальные концепции, интерфейсы и графику. Работа с инструментами, такими как Adobe Photoshop, Figma, и понимание основ UX/UI — важные аспекты профессии.",
      "Навыки: Figma, Adobe Photoshop, Illustrator, UX/UI. Средняя зарплата: от 70 000 руб.",
      "IT"
  ]
];

$pvk_array = [
    'personal' => [
        [ 'ReadinessToDefendHomeland', 'Готовность к защите Родины с оружием в руках' ],
        [ 'MilitaryProfessionalOrientation', 'Военно-профессиональная направленность' ],
        [ 'DirectInternalMilitaryMotives', 'Прямые внутренние мотивы военно-профессиональной деятельности' ],
        [ 'StrivingForProfessionalExcellence', 'Стремление к профессиональному совершенству' ],
        [ 'AdequateSelfEsteem', 'Адекватная самооценка' ],
        [ 'Independence', 'Самостоятельность' ],
        [ 'PunctualityPedantry', 'Пунктуальность, педантичность' ],
        [ 'Discipline', 'Дисциплинированность' ],
        [ 'AccuracyAtWork', 'Аккуратность в работе' ],
        [ 'OrganizationSelfDiscipline', 'Организованность, самодисциплина' ],
        [ 'DiligenceExecutiveAbility', 'Старательность, исполнительность' ],
        [ 'Responsibility', 'Ответственность' ],
        [ 'Industriousness', 'Трудолюбие' ],
        [ 'Initiative', 'Инициативность' ],
        [ 'SelfCriticism', 'Самокритичность' ],
        [ 'OptimismPositiveEmotions', 'Оптимизм, доминирование положительных эмоций' ],
        [ 'SelfControlEmotionalBalance', 'Самообладание, эмоциональная уравновешенность, выдержка' ],
        [ 'SelfControlSelfObservation', 'Самоконтроль, способность к самонаблюдению' ],
        [ 'Foresight', 'Предусмотрительность' ],
        [ 'FrustrationTolerance', 'Фрустрационная толерантность (отсутствие агрессивности или депрессивности в ситуациях неудач)' ],
        [ 'SelfMobilizingReactionToObstacles', 'Самомобилизующийся тип реакции на препятствия, возникающие на пути к достижению цели' ],
        [ 'Internality', 'Интернальность (погруженность в себя, самодостаточность, необщительность)' ],
        [ 'Externality', 'Экстернальность (ориентация на взаимодействие с людьми, общительность)' ],
        [ 'Intrapunitiveness', 'Интрапунитивность (ориентация на собственные силы, уверенность в себе, чувство самоэффективности)' ],
        [ 'Extrapunitiveness', 'Экстрапунитивность (ориентация на помощь других людей, надежда на благоприятные обстоятельства, неуверенность в себе)' ],
        [ 'AbilityToPlanActivities', 'Способность планировать свою деятельность во времени' ],
        [ 'AbilityToOrganizeActivities', 'Способность организовывать свою деятельность в условиях большого потока информации и разнообразия поставленных задач' ],
        [ 'AbilityToTakeResponsibility', 'Способность брать на себя ответственность за принимаемые решения и действия' ],
        [ 'AbilityToMakeDecisionsInUnusualSituations', 'Способность принимать решение в нестандартных ситуациях' ],
        [ 'AbilityToActRationallyInExtremeSituations', 'Способность рационально действовать в экстремальных ситуациях' ],
        [ 'AbilityToActEffectivelyInTimePressure', 'Способность эффективно действовать (также быстро принимать решения) в условиях дефицита времени' ],
        [ 'AbilityToTolerateUnpleasantSensations', 'Способность переносить неприятные ощущения (дурной запах, шум, грязь, холодная вода, ожог, царапина, удар электрического тока и т.д.) без потрясений' ],
        [ 'AbilityToDefendOpinion', 'Способность аргументировано отстаивать свое мнение' ],
        [ 'AbilityToSwitchActivities', 'Способность к переключениям с одной деятельности на другую' ],
        [ 'AbilityToOvercomeFear', 'Способность преодолевать страх' ],
        [ 'Decisiveness', 'Решительность' ],
        [ 'StrongWill', 'Сильная воля' ],
        [ 'Courage', 'Смелость' ],
        [ 'SenseOfDuty', 'Чувство долга' ],
        [ 'Honesty', 'Честность' ],
        [ 'Decency', 'Порядочность' ],
        [ 'Comradeship', 'Товарищество'],
    ],
    'intellectual' => [
        [ 'VisualSizeEstimation', 'Зрительная оценка размеров предметов' ],
        [ 'VisualDistancePerception', 'Зрительное восприятие расстояний между предметами' ],
        [ 'EyeMeasurement', 'Глазомер: линейный, угловой, объемный' ],
        [ 'DynamicEyeMeasurement', 'Глазомер динамический (способность оценивать направление и скорость движения предмета)' ],
        [ 'AbilityToDistinguishFigureOnLowContrastBackground', 'Способность к различению фигуры (предмета, отметки, сигнала и пр.) на малоконтрастном фоне' ],
        [ 'AbilityToDistinguishDisguisedObjects', 'Способность различать и опознавать замаскированные объекты' ],
        [ 'AbilityToPerceiveSpatialRelationships', 'Способность к восприятию пространственного соотношения предметов' ],
        [ 'AccuracyOfSoundSourceDirection', 'Точность и оценка направления на источник звука' ],
        [ 'AbilityToRecognizeRhythms', 'Способность узнавать и различать ритмы' ],
        [ 'SpeechHearing', 'Речевой слух (восприятие устной речи)' ],
        [ 'TimeIntervalDiscrimination', 'Различение отрезков времени' ],
        [ 'AbilityToRecognizeDeviationsVisually', 'Способность к распознаванию небольших отклонений параметров технологических процессов от заданных значений по визуальным признакам' ],
        [ 'AbilityToRecognizeDeviationsAudibly', 'Способность к распознаванию небольших отклонений параметров технологических процессов от заданных значений по акустическим признакам' ],
        [ 'AbilityToRecognizeDeviationsKinesthetically', 'Способность к распознаванию небольших отклонений параметров технологических процессов от заданных значений по кинестетическим признакам' ],
        [ 'AbilityToVisualRepresentations', 'Способность к зрительным представлениям' ],
        [ 'AbilityToSpatialImagination', 'Способность к пространственному воображению' ],
        [ 'AbilityToFigurativeRepresentation', 'Способность к образному представлению предметов, процессов и явлений' ],
        [ 'AbilityToVisualizeNewPhenomenon', 'Способность наглядно представлять себе новое явление, ранее, не встречающееся в опыте, или старое, но в новых условиях' ],
        [ 'AbilityToTranslateImageToVerbalDescription', 'Способность к переводу образа в словесное описание' ],
        [ 'AbilityToRecreateImageFromVerbalDescription', 'Способность к воссозданию образа по словесному описанию' ],
        [ 'AnalyticalThinking', 'Аналитичность (способность выделять отдельные элементы действительности, способность к классификации)' ],
        [ 'SyntheticThinking', 'Синтетичность (способность к обобщениям, установлению связей, закономерностей, формирование понятий)' ],
        [ 'TranssonanceThinking', 'Транссонантность (способность к актуализации и вовлечению в процесс мышления информации, хранящейся в памяти, ассоциативность мышления)' ],
        [ 'LogicalThinking', 'Логичность' ],
        [ 'CreativeThinking', 'Креативность (способность порождать необычные идеи, отклоняться от традиционных схем мышления)' ],
        [ 'OperativeThinking', 'Оперативность (скорость мыслительных процессов, интеллектуальная лабильность)' ],
        [ 'ObjectivityOfThinking', 'Предметность (объекты реального мира и их признаки)' ],
        [ 'ImageryOfThinking', 'Образность (наглядные образы, схемы, планы и т.д.)' ],
        [ 'AbstractnessOfThinking', 'Абстрактность (абстрактные образы, понятия)' ],
        [ 'VerbalityOfThinking', 'Вербальность (устная и письменная речь)' ],
        [ 'CalculativeThinking', 'Калькулятивность (цифровой материал)' ],
        [ 'VisualLongTermMemoryFaces', 'на лица' ],
        [ 'VisualLongTermMemoryObjects', 'на образы предметного мира' ],
        [ 'VisualLongTermMemorySymbols', 'на условные обозначения (знаки, символы, планы, схемы, графики)' ],
        [ 'VisualLongTermMemoryNumbersDates', 'на цифры, даты' ],
        [ 'VisualLongTermMemoryWordsPhrases', 'на слова и фразы' ],
        [ 'VisualLongTermMemoryTextSemantics', 'на семантику текста' ],
        [ 'VisualShortTermMemoryFaces', 'на лица' ],
        [ 'VisualShortTermMemoryObjects', 'на образы предметного мира' ],
        [ 'VisualShortTermMemorySymbols', 'на условные обозначения (знаки, символы, планы, схемы, графики)' ],
        [ 'VisualShortTermMemoryNumbersDates', 'на цифры, даты' ],
        [ 'VisualShortTermMemoryWordsPhrases', 'на слова и фразы' ],
        [ 'VisualShortTermMemoryTextSemantics', 'на семантику текста' ],
        [ 'AuditoryLongTermMemoryVoices', 'на голоса' ],
        [ 'AuditoryLongTermMemoryNumbers', 'на цифры' ],
        [ 'AuditoryLongTermMemorySignals', 'на условные сигналы' ],
        [ 'AuditoryLongTermMemoryMelodies', 'на мелодии' ],
        [ 'AuditoryLongTermMemoryMessageSemantics', 'на семантику сообщений' ],
        [ 'AuditoryShortTermMemoryNumbers', 'на цифры' ],
        [ 'AuditoryShortTermMemoryMessageSemantics', 'на семантику сообщений' ],
        [ 'KinestheticMemorySimpleMovements', 'на простые движения' ],
        [ 'KinestheticMemoryComplexMovements', 'на сложные движения' ],
        [ 'KinestheticMemoryBodyPosition', 'на положение и перемещение тела в пространстве' ],
        [ 'TactileMemory', 'Тактильная память' ],
        [ 'OlfactoryMemory', 'Обонятельная память' ],
        [ 'GustatoryMemory', 'Вкусовая память' ],
    ],
    'physical' => [
        [ 'AnthropometricCharacteristics', 'Антропометрические характеристики (в соответствии с требованиями профессии)' ],
        [ 'BodyType', 'Особенности телосложения (в соответствии с требованиями профессии)' ],
        [ 'GoodPhysicalDevelopment', 'Хорошее общее физическое развитие – выносливость, координированность, сила, быстрота' ],
        [ 'PhysicalConditioning', 'Физическая подготовленность к воздействию неблагоприятных факторов профессиональной деятельности' ],
    ],
    'physiological' => [
        [ 'DynamicLoadTolerance', 'Переносимость динамических физических нагрузок' ],
        [ 'StaticLoadTolerance', 'Переносимость статических физических нагрузок' ],
        [ 'RapidTransitionToWork', 'Быстрый переход из состояния покоя к интенсивной работе' ],
        [ 'SleepDeprivationTolerance', 'Сохранение работоспособности при недостатке сна' ],
        [ 'FatigueTolerance', 'Сохранение работоспособности при развивающемся утомлении' ],
        [ 'MonotonyTolerance', 'Сохранение бдительности в условиях однообразной деятельности (монотонии)' ],
        [ 'VigilanceInAnticipation', 'Сохранение бдительности в режиме ожидания' ],
        [ 'TemperatureTolerance', 'Сохранение работоспособности в некомфортных температурных условиях' ],
        [ 'GLoadTolerance', 'Сохранение работоспособности в условиях знакопеременных перегрузок (в том числе укачивания)' ],
        [ 'VibrationTolerance', 'Сохранение работоспособности в условиях воздействия вибрации' ],
        [ 'MultiDirectionalGLoadTolerance', 'Сохранение работоспособности в условиях воздействия разнонаправленных перегрузок' ],
        [ 'BarometricTolerance', 'Сохранение работоспособности в условиях гипо(гипер) барометрических колебаний' ],
        [ 'HypoxiaTolerance', 'Сохранение работоспособности в условиях пониженного парциального давления кислорода' ],
        [ 'HypocapniaTolerance', 'Сохранение работоспособности в условиях пониженного парциального давления углекислого газа' ],
        [ 'BasicNeedsDeprivationTolerance', 'Сохранение работоспособности в условиях ограничения возможностей удовлетворения базовых жизненных потребностей (голод, жажда, отдых, сексуальная потребность)' ],
        [ 'ClimaticTolerance', 'Сохранение работоспособности в разных природно-климатических условиях' ],
        [ 'EnvironmentalAdaptability', 'Способность переадаптироваться к новым средовым условиям' ],
    ],
    'psychophysiological' => [
        [ 'EnergyVitality', 'Энергичность, витальность (активность)' ],
        [ 'MentalEfficiency', 'Умственная работоспособность' ],
        [ 'PhysicalEndurance', 'Физическая работоспособность (выносливость)' ],
        [ 'EmotionalStability', 'Нервно-эмоциональная устойчивость, выносливость по отношению к эмоциональным нагрузкам' ],
    ],
    'operational' => [
        [ 'VisualAcuity', 'Острота зрения' ],
        [ 'VisualAdaptation', 'Адаптация зрения к темноте, свету' ],
        [ 'ContrastSensitivity', 'Контрастная чувствительность монохроматического зрения' ],
        [ 'ColorDiscrimination', 'Цветовая дифференциальная чувствительность' ],
        [ 'VisualStability', 'Устойчивость зрительной чувствительности во времени' ],
        [ 'AuditoryAcuity', 'Острота слуха' ],
        [ 'AuditoryContrastSensitivity', 'Контрастная чувствительность слуха' ],
        [ 'AuditoryDiscrimination', 'Слуховая дифференциальная чувствительность (способность различать: тембр, длительность, высоту, силу звука, ритм, фоновые или разнообразные шумы)' ],
        [ 'SoundTolerance', 'Переносимость длительно действующего звукового раздражителя' ],
        [ 'TactileSensitivity', 'Чувствительность (осязание) пальцев' ],
        [ 'VibrationSensitivity', 'Вибрационная чувствительность' ],
        [ 'KinestheticSensitivity', 'Мышечно-суставная чувствительность усилий или сопротивления' ],
        [ 'BalanceSensation', 'Ощущение равновесия' ],
        [ 'AccelerationSensation', 'Ощущение ускорения' ],
        [ 'OlfactorySensitivity', 'Обонятельная чувствительность' ],
        [ 'TasteDiscrimination', 'Способность узнавать и различать вкусовые ощущения' ],
        [ 'AttentionSpan', 'Объем внимания (количество объектов, на которые может быть направлено внимание при их одновременном восприятии)' ],
        [ 'AttentionConcentration', 'Концентрированность внимания' ],
        [ 'AttentionStability', 'Устойчивость внимания во времени' ],
        [ 'AttentionSwitching', 'Переключаемость внимания (способность быстрого переключения внимания с одного объекта на другой или с одной деятельности на другую)' ],
        [ 'AttentionDistribution', 'Способность к распределению внимания между несколькими объектами или видами деятельности' ],
        [ 'AttentionResistanceToInterference', 'Помехоустойчивость внимания' ],
        [ 'ChangeDetection', 'Способность подмечать изменения в окружающей обстановке, не сосредотачивая сознательно на них внимание' ],
        [ 'NoticingSubtleChanges', 'Умение подмечать незначительные (малозаметные) изменения в исследуемом объекте, в показаниях приборов' ],
        [ 'VisualMotorReaction', 'Способность реагировать на неожиданный зрительный сигнал посредством определённых движений' ],
        [ 'AuditoryMotorReaction', 'Способность реагировать на неожиданный слуховой сигнал посредством определённых движений' ],
        [ 'SensorimotorCoordination', 'Согласованность движений с процессами восприятия (сложноорганизованная деятельность)' ],
        [ 'SensorimotorTracking', 'Способность к сенсомоторному слежению за движущимся объектом' ],
        [ 'FineMotorSkills', 'Способность к выполнению мелких точных движений' ],
        [ 'ComplexMotorSkills', 'Способность к выполнению сложных двигательных действий (актов)' ],
        [ 'SmoothMotorMovements', 'Способность к выполнению плавных соразмерных движений' ],
        [ 'DominantHandCoordination', 'Координация движений ведущей руки' ],
        [ 'BimanualCoordination', 'Координация движений обеих рук' ],
        [ 'HandFootCoordination', 'Координация движений рук и ног' ],
        [ 'HandFingerCoordination', 'Координация работы кистей рук и пальцев' ],
        [ 'HandStability', 'Твердость руки, устойчивость кистей рук (низкий тремор)' ],
        [ 'RapidWriting', 'Умение быстро записывать' ],
        [ 'GoodHandwriting', 'Красивый почерк' ],
        [ 'PhysicalStrength', 'Физическая сила' ],
        [ 'RapidSkillAcquisition', 'Способность к быстрой выработке сенсомоторных навыков' ],
        [ 'RapidSkillAdaptation', 'Способность к быстрой перестройке сенсомоторных навыков' ],
        [ 'MovementPlasticity', 'Пластичность и выразительность движений' ],
        [ 'ClearSpeech', 'Отсутствие дефектов речи, хорошая дикция' ],
        [ 'SpeechEndurance', 'Способность речевого аппарата к интенсивной и длительной работе' ],
        [ 'ToneVariation', 'Способность к изменению тембра' ],
        [ 'VolumeVariation', 'Способность к изменению силы звучания' ],
    ],
];
$categories = ["personal", "intellectual", "physical", "physiological", "psychophysiological", "operational"];
$i = 0;
foreach ($pvk_array as $pvk_category) {
    foreach ($pvk_category as $pvk_data) {
        try {
            $pvk = new \models\Pvk($database->getConnection());
            $pvk->create($pvk_data[0], $pvk_data[1], $categories[$i]);
        } catch (PDOException $e) {
            echo $e->getMessage() . "<br>";
        }
    }
    $i++;
}

foreach ($professions_array as $profession) {
    try {
        $profLoader = new \models\Profession($database->getConnection());
        $profLoader->create($profession[0], $profession[1], $profession[2], $profession[3]);
    } catch (PDOException $e) {
        echo $e->getMessage() . "<br>";
    }
}
